services:
  db:
    image: postgres:14.19-alpine
    env_file:
      - .env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-recruitment_names_test}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

volumes:
  postgres_test_data:
